version: "3.8"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: on-failure
    container_name: timelog_sql-server
    environment:
      ACCEPT_EULA: y
      SA_PASSWORD: Your_password123
    ports:
      - 20401:1433
    volumes:
      - timelog-data:/var/opt/mssql

volumes:
  timelog-data: